name: Hello World

on: push

jobs:
    hello-job:
      strategy:
        matrix:
          os: 
            - ubuntu-latest
            - windows-latest
          versions:   
            - 12
            - 14
      runs-on: ubuntu-latest
      steps:
        - name: Echo text
          run: echo "Hello, world!"