name: Hello World

on: push

jobs:
    hello-job:
      strategy:
        matrix:
          os: 
            - ubuntu-latest
            - windows-latest
          versions: 
            - 10
            - 11  
      runs-on: ubuntu-latest
      steps:
        - name: Echo text
          run: echo "Hello, world!"